name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sudo if not installed, github has it installed and needs apt to run with sudo
      run: apt install sudo || true
    - name: Install dependencies of autogen
      run: |
        sudo apt update
        sudo apt install -y -V autoconf autopoint gcc pkg-config \
                          libglib2.0-dev libgtk-3-dev libpopt-dev \
                          make gettext
    - name: autogen
      run: ./autogen.sh
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
